import type { PluggedK } from "./types.d.ts"

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export function idNoCtx(k: PluggedK) {
    return k.grindleUtil.makeStringEnum([
        "agent",
        "animate",
        "area",
        "areaEffector",
        "anchor",
        "body",
        "buoyancyEffector",
        "circle",
        "color",
        "constantForce",
        "doubleJump",
        "ellipse",
        "fixed",
        "follow",
        "health",
        "layer",
        "lifespan",
        "mask",
        "move",
        "named",
        "offscreen",
        "opacity",
        "outline",
        "pathfinder",
        "particles",
        "patrol",
        "platformEffector",
        "pointEffector",
        "polygon",
        "pos",
        "rect",
        "rotate",
        "scale",
        "sentry",
        "shader",
        "sprite",
        "state",
        "stay",
        "surfaceEffector",
        "text",
        "textInput",
        "timer",
        "tile",
        "uvquad",
        "z",
    ])
}
